package __PACKAGE__;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Native application controllers compiled from the shared service/features declaration. */
public class SocialActivity extends Activity {
    private final Handler main = new Handler(Looper.getMainLooper());
    private ApiClient api; private SessionStore sessions; private JSONObject session;
    private LinearLayout host, content, navigation, statusBox; private TextView status;
    private ProgressBar loading; private Button retry, activatedButton; private int pendingRequests; private String loadingMessage="Loading…";
    private int selected, revision; private boolean foreground; private String conversation;
    private org.maplibre.android.maps.MapView mapView;
    private android.location.LocationManager locations;
    private android.location.LocationListener locationListener;
    private NativeCamera camera;
    private boolean locationConsent, changingConsent;
    private long messageCursor; private boolean loadingMessages;
    private final int accent = __ACCENT__, background = __BACKGROUND__, surface = __SURFACE__, ink = __TEXT__, muted = __MUTED__, danger = __DANGER__;
    private final String[] titles = __TITLES__;
    private final String[] features = __FEATURES__;
    private final int[] icons = __ICONS__;
    private interface Result { void accept(JSONObject value); }
    private JSONObject object(Object... values) { JSONObject result = new JSONObject(); try { for (int i=0;i<values.length;i+=2) result.put((String)values[i], values[i+1]); } catch(JSONException error) { throw new IllegalArgumentException(error); } return result; }
    private int dp(int value) { return Math.round(value * getResources().getDisplayMetrics().density); }
    private android.graphics.drawable.GradientDrawable shape(int color) { android.graphics.drawable.GradientDrawable result = new android.graphics.drawable.GradientDrawable(); result.setColor(color); result.setCornerRadius(dp(__RADIUS__)); return result; }
    private LinearLayout column() { LinearLayout view = new LinearLayout(this); view.setOrientation(LinearLayout.VERTICAL); return view; }
    private TextView label(String value, int size) { TextView view = new TextView(this); view.setText(value); view.setTextColor(ink); view.setTextSize(size); view.setPadding(0,dp(8),0,dp(8)); return view; }
    private android.graphics.drawable.Drawable controlBackground(int fill, boolean outlined) {
        android.graphics.drawable.GradientDrawable base=shape(fill);if(outlined)base.setStroke(dp(1),blend(ink,surface,0.12f));
        return new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(blend(ink,fill,0.12f)),base,null);
    }
    private int blend(int foregroundColor,int backgroundColor,float fraction){return Color.rgb(Math.round(Color.red(foregroundColor)*fraction+Color.red(backgroundColor)*(1-fraction)),Math.round(Color.green(foregroundColor)*fraction+Color.green(backgroundColor)*(1-fraction)),Math.round(Color.blue(foregroundColor)*fraction+Color.blue(backgroundColor)*(1-fraction)));}
    private Button button(String text, Runnable action) { Button view = new Button(this); view.setText(text); view.setAllCaps(false); view.setTextSize(15);view.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));view.setTextColor(ink); view.setBackground(controlBackground(surface,true)); view.setMinHeight(dp(52));view.setPadding(dp(16),dp(10),dp(16),dp(10)); view.setOnClickListener(v -> {activatedButton=view;action.run();activatedButton=null;}); return view; }
    private Button primary(String text,Runnable action){Button view=button(text,action);view.setBackground(controlBackground(accent,false));return view;}
    private Button quiet(String text,Runnable action){Button view=button(text,action);view.setBackground(controlBackground(background,false));view.setTextColor(muted);return view;}
    private EditText field(String hint, boolean password) { EditText view = new EditText(this); view.setHint(hint);view.setContentDescription(hint);view.setHintTextColor(muted);view.setTextSize(16); view.setTextColor(ink); view.setSingleLine(true);view.setPadding(dp(16),dp(16),dp(16),dp(16));view.setMinHeight(dp(56));view.setBackground(controlBackground(surface,true));view.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_NEXT); if(password) view.setInputType(129);view.setOnFocusChangeListener((v,focus)->{android.graphics.drawable.GradientDrawable base=shape(surface);base.setStroke(dp(focus?2:1),focus?ink:blend(ink,surface,0.12f));v.setBackground(base);}); return view; }
    private void add(LinearLayout target, View view) { LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1,-2); lp.bottomMargin=dp(12); target.addView(view,lp); }
    private LinearLayout scroll(LinearLayout parent) { ScrollView scroll = new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false); LinearLayout list=column();list.setPadding(0,0,0,dp(20));scroll.addView(list); parent.addView(scroll,new LinearLayout.LayoutParams(-1,0,1)); return list; }
    private void notice(String message) { status.setText(message); status.setTextColor(muted);loading.setVisibility(pendingRequests>0?View.VISIBLE:View.GONE);statusBox.setVisibility(message.isEmpty()&&pendingRequests==0?View.GONE:View.VISIBLE);retry.setVisibility(View.GONE); }
    private void error(String message,Runnable again){notice(message);status.setTextColor(danger);if(again!=null){retry.setVisibility(View.VISIBLE);retry.setOnClickListener(v->again.run());}}
    private void busy(boolean active){pendingRequests=Math.max(0,pendingRequests+(active?1:-1));loading.setVisibility(pendingRequests>0?View.VISIBLE:View.GONE);if(pendingRequests>0)notice(loadingMessage);else if(status.getText().toString().equals(loadingMessage))notice("");}
    private void request(String method,String path,JSONObject body,Result callback) {
        int expected=revision;final Button trigger=activatedButton;activatedButton=null;if(trigger!=null){trigger.setEnabled(false);trigger.setAlpha(0.5f);}loadingMessage=path.equals("/auth/login")?"Signing in…":path.equals("/auth/register")?"Creating account…":"Loading…";busy(true); api.request(method,path,body,null,false,(value,bytes,error,code)-> {
            if(expected!=revision || isFinishing()) return;
            busy(false);if(trigger!=null){trigger.setEnabled(true);trigger.setAlpha(1);}
            if(code==401&&session!=null) { signOut(); return; }
            if(error!=null) { error(error,method.equals("GET")?()->request(method,path,body,callback):null); return; }
            notice(""); callback.accept(value);
        });
    }
    @Override public void onCreate(Bundle state) {
        super.onCreate(state); api=new ApiClient(); sessions=new SessionStore(this); session=sessions.load();
        if(session!=null) api.token=session.optString("token");
        selected=state==null?0:state.getInt("tab",0); conversation=state==null?null:state.getString("conversation");
        host=column(); host.setBackgroundColor(background); setContentView(host);
        host.setOnApplyWindowInsetsListener((view,insets)-> { view.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom()); if(Build.VERSION.SDK_INT>=30 && view.getWindowInsetsController()!=null) view.getWindowInsetsController().setSystemBarsAppearance(24,24); else view.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR); return insets; }); host.requestApplyInsets();
        if(session==null) auth(false); else shell();
    }
    private void reset() { revision++;stopFeatures();pendingRequests=0;host.removeAllViews();content=new LinearLayout(this){@Override protected void onMeasure(int width,int height){int cap=dp(620);if(View.MeasureSpec.getSize(width)>cap)width=View.MeasureSpec.makeMeasureSpec(cap,View.MeasureSpec.EXACTLY);super.onMeasure(width,height);}};content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(__PADDING__),dp(8),dp(__PADDING__),0);LinearLayout.LayoutParams contentParams=new LinearLayout.LayoutParams(-1,0,1);contentParams.gravity=Gravity.CENTER_HORIZONTAL;host.addView(content,contentParams);statusBox=column();statusBox.setPadding(dp(14),dp(8),dp(14),dp(8));statusBox.setBackground(shape(surface));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);loading=new ProgressBar(this);loading.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(ink));line.addView(loading,new LinearLayout.LayoutParams(dp(20),dp(20)));status=label("",13);status.setPadding(dp(10),dp(4),0,dp(4));status.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);line.addView(status,new LinearLayout.LayoutParams(0,-2,1));statusBox.addView(line);retry=quiet("Try again",()->{});statusBox.addView(retry);statusBox.setVisibility(View.GONE);content.addView(statusBox); }
    private void input(LinearLayout form,String title,EditText view){TextView caption=label(title,13);caption.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));caption.setPadding(dp(2),0,0,dp(5));form.addView(caption);LinearLayout.LayoutParams inputParams=new LinearLayout.LayoutParams(-1,-2);inputParams.bottomMargin=dp(8);form.addView(view,inputParams);}
    private void auth(boolean register) {
        reset();LinearLayout form=scroll(content);form.setGravity(Gravity.CENTER_VERTICAL);
        FrameLayout hero=new FrameLayout(this);ImageView cameraIcon=new ImageView(this);cameraIcon.setImageResource(R.drawable.app_icon_camera);cameraIcon.setImageTintList(android.content.res.ColorStateList.valueOf(ink));cameraIcon.setPadding(dp(14),dp(14),dp(14),dp(14));cameraIcon.setBackground(shape(accent));cameraIcon.setRotation(-8);cameraIcon.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);FrameLayout.LayoutParams emblem=new FrameLayout.LayoutParams(dp(56),dp(56),Gravity.CENTER);hero.addView(cameraIcon,emblem);form.addView(hero,new LinearLayout.LayoutParams(-1,dp(64)));
        View viewport=(View)form.getParent();viewport.addOnLayoutChangeListener((v,left,top,right,bottom,oldLeft,oldTop,oldRight,oldBottom)->{
            int available=bottom-top;if(available<=0)return;
            int heroHeight=Math.max(dp(32),Math.min(dp(104),available-dp(register?640:560)));
            if(hero.getLayoutParams().height!=heroHeight){hero.getLayoutParams().height=heroHeight;int iconSize=Math.max(dp(28),Math.min(dp(88),heroHeight-dp(8)));FrameLayout.LayoutParams iconParams=(FrameLayout.LayoutParams)cameraIcon.getLayoutParams();iconParams.width=iconSize;iconParams.height=iconSize;cameraIcon.setLayoutParams(iconParams);int inset=Math.max(dp(6),iconSize/4);cameraIcon.setPadding(inset,inset,inset,inset);hero.requestLayout();}
        });
        TextView brand=label(__NAME__,30);brand.setGravity(Gravity.CENTER);brand.setTypeface(android.graphics.Typeface.create("sans-serif-black",0));brand.setLetterSpacing(-0.035f);brand.setPadding(0,0,0,dp(6));form.addView(brand);
        TextView invitation=label(register?"Your people. Your moments.":"Good to see you again.",16);invitation.setTextColor(muted);invitation.setGravity(Gravity.CENTER);invitation.setPadding(0,0,0,dp(16));form.addView(invitation);
        TextView title=label(register?"Create your account":"Sign in",21);title.setPadding(0,0,0,dp(4));title.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));add(form,title);
        EditText username=field("e.g. alex",false), password=field(register?"At least 12 characters":"Enter your password",true), display=field("How friends see you",false);username.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);username.setAutofillHints(View.AUTOFILL_HINT_USERNAME);password.setAutofillHints(View.AUTOFILL_HINT_PASSWORD);input(form,"Username",username);if(register)input(form,"Display name",display);input(form,"Password",password);
        CheckBox visible=new CheckBox(this);visible.setText("Show password");visible.setTextColor(muted);visible.setTextSize(13);visible.setButtonTintList(android.content.res.ColorStateList.valueOf(ink));visible.setMinHeight(dp(48));visible.setOnCheckedChangeListener((v,show)->{int cursor=password.getSelectionStart();password.setTransformationMethod(show?null:android.text.method.PasswordTransformationMethod.getInstance());password.setSelection(Math.max(0,cursor));});add(form,visible);
        Runnable submit=()->{String handle=username.getText().toString().trim();String secret=password.getText().toString();boolean valid=true;if(handle.isEmpty()||(register&&!handle.matches("[A-Za-z0-9_]{3,24}"))){username.setError("Use 3–24 letters, numbers or underscores");valid=false;}if(secret.isEmpty()||(register&&secret.length()<12)){password.setError(register?"Use at least 12 characters":"Enter your password");valid=false;}if(register&&display.getText().toString().trim().isEmpty()){display.setError("Enter a display name");valid=false;}if(!valid)return;
            request("POST",register?"/auth/register":"/auth/login",register?object("username",handle,"password",secret,"display_name",display.getText().toString().trim()):object("username",handle,"password",secret),value->{try{sessions.save(value);session=value;api.token=value.optString("token");android.view.inputmethod.InputMethodManager keyboard=(android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);keyboard.hideSoftInputFromWindow(password.getWindowToken(),0);shell();}catch(Exception failure){error("Secure storage failed: "+failure.getMessage(),null);}});};
        Button submitButton=primary(register?"Create account":"Sign in",submit);add(form,submitButton);password.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);password.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_DONE){if(submitButton.isEnabled())submitButton.performClick();return true;}return false;});
        add(form,quiet(register?"Already a member? Sign in":"New here? Create an account",()->auth(!register)));
    }
    private void signOut() { sessions.clear(); session=null; api.token=""; conversation=null; auth(false); }
    private void shell() {
        reset(); navigation=new LinearLayout(this);navigation.setGravity(Gravity.CENTER);navigation.setPadding(dp(8),dp(8),dp(8),dp(8));navigation.setBackgroundColor(surface);navigation.setElevation(dp(6));
        for(int i=0;i<titles.length;i++){final int index=i;Button tab=button(titles[i],()->{selected=index;conversation=null;shell();});tab.setTextSize(11);tab.setPadding(dp(2),dp(8),dp(2),dp(7));tab.setMinWidth(0);tab.setMinimumWidth(0);tab.setCompoundDrawablePadding(dp(5));tab.setBackground(controlBackground(i==selected?accent:surface,false));tab.setTextColor(i==selected?ink:muted);tab.setSelected(i==selected);tab.setContentDescription(titles[i]+(i==selected?", selected":""));android.graphics.drawable.Drawable icon=getDrawable(icons[i]).mutate();icon.setTint(i==selected?ink:muted);icon.setBounds(0,0,dp(23),dp(23));tab.setCompoundDrawables(null,icon,null,null);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(64),1);lp.setMarginStart(dp(3));lp.setMarginEnd(dp(3));navigation.addView(tab,lp);}
        host.addView(navigation);
        if(conversation!=null) { conversation(conversation); return; }
        LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);TextView headingTitle=label(titles[selected],30);headingTitle.setTypeface(android.graphics.Typeface.create("sans-serif-black",0));heading.addView(headingTitle,new LinearLayout.LayoutParams(0,-2,1));if(!features[selected].equals("camera")){Button refresh=quiet("Refresh",this::shell);heading.addView(refresh,new LinearLayout.LayoutParams(-2,dp(48)));}if(!features[selected].equals("camera"))add(content,heading);
        switch(features[selected]) { case "camera": cameraScreen(); break; case "inbox": inbox(); break; case "stories": stories(); break; case "friendMap": friendMap(); break; case "account": account(); break; default: throw new IllegalStateException("Unknown compiled feature"); }
    }
    private void empty(LinearLayout list,int icon,String title,String description){LinearLayout card=column();card.setGravity(Gravity.CENTER);card.setPadding(dp(24),dp(32),dp(24),dp(32));card.setBackground(shape(surface));ImageView image=new ImageView(this);image.setImageResource(icon);image.setImageTintList(android.content.res.ColorStateList.valueOf(muted));card.addView(image,new LinearLayout.LayoutParams(dp(44),dp(44)));TextView heading=label(title,20);heading.setGravity(Gravity.CENTER);heading.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));add(card,heading);TextView text=label(description,15);text.setTextColor(muted);text.setGravity(Gravity.CENTER);add(card,text);add(list,card);}
    private void inbox() { add(content,button("Find friends",this::friends)); LinearLayout list=scroll(content); request("GET","/conversations",null,value->{ JSONArray items=value.optJSONArray("conversations"); if(items.length()==0)empty(list,R.drawable.app_icon_chat,"Start a conversation","Find your friends and send your first hello."); for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);add(list,button(item.optString("display_name"),()->{conversation=item.optString("id");shell();}));} }); }
    private void friends() {
        reset(); add(content,button("Back",this::shell)); EditText query=field("Search username",false); add(content,query); LinearLayout list=scroll(content);
        add(content,button("Search",()->{list.removeAllViews();request("GET","/users?q="+android.net.Uri.encode(query.getText().toString()),null,value->{JSONArray items=value.optJSONArray("users");for(int i=0;i<items.length();i++){JSONObject user=items.optJSONObject(i);add(list,button("Add @"+user.optString("username"),()->request("POST","/friend-requests",object("user_id",user.optString("id")),result->notice("Friend request sent"))));}});}));
        request("GET","/friend-requests",null,value->{JSONArray items=value.optJSONArray("requests");for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);if(item.optString("recipient").equals(session.optJSONObject("user").optString("id")))add(list,button("Accept @"+item.optString("username"),()->request("POST","/friend-requests/"+item.optString("id")+"/accept",object(),result->friends())));}});
        request("GET","/friends",null,value->{JSONArray items=value.optJSONArray("friends");for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);add(list,button("Chat with "+item.optString("display_name"),()->request("POST","/conversations",object("user_id",item.optString("id")),result->{conversation=result.optString("id");shell();})));add(list,button("Remove @"+item.optString("username"),()->new AlertDialog.Builder(this).setMessage("Remove this friend?").setNegativeButton("Cancel",null).setPositiveButton("Remove",(d,w)->request("DELETE","/friends/"+item.optString("id"),null,result->friends())).show()));}});
    }
    private void conversation(String id) {
        messageCursor=0; loadingMessages=false;
        add(content,button("Back to conversations",()->{conversation=null;shell();})); LinearLayout messages=scroll(content); EditText composer=field("Message",false); add(content,composer);
        add(content,button("Send",()->{String text=composer.getText().toString().trim();if(SharedLogic.f_canSendMessage(text.codePointCount(0,text.length()),0)!=1){notice("Enter a message of up to 2,000 characters.");return;}request("POST","/conversations/"+id+"/messages",object("text",text),value->{composer.setText("");loadMessages(id,messages);});}));
        add(content,button("Send a photo",this::pickPhoto)); loadMessages(id,messages);
        int expected=revision; main.postDelayed(new Runnable(){public void run(){if(foreground&&expected==revision){loadMessages(id,messages);main.postDelayed(this,5000);}}},5000);
    }
    private void loadMessages(String id,LinearLayout list) {
        if(loadingMessages)return;loadingMessages=true;int expected=revision;
        api.request("GET","/conversations/"+id+"/messages?after="+messageCursor,null,null,false,(value,bytes,error,code)->{
            if(expected!=revision)return;loadingMessages=false;
            if(code==401){signOut();return;}if(error!=null){notice(error);return;}
            JSONArray items=value.optJSONArray("messages");
            for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);long messageId=item.optLong("id");if(messageId<=messageCursor)continue;messageCursor=messageId;
                add(list,label((item.optString("sender").equals(session.optJSONObject("user").optString("id"))?"You: ":"")+item.optString("text"),16));if(!item.isNull("media_id"))media(list,item.optString("media_id"));}
            if(items.length()==100)loadMessages(id,list);
        });
    }
    private void media(LinearLayout list,String id) { ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setContentDescription("Shared photo loading");list.addView(image,new LinearLayout.LayoutParams(-1,dp(260)));int expected=revision;api.request("GET","/media/"+id,null,null,true,(value,bytes,error,code)->{if(expected!=revision)return;if(error!=null){image.setContentDescription("Photo unavailable: "+error);notice(error);}else{image.setImageBitmap(BitmapFactory.decodeByteArray(bytes,0,bytes.length));image.setContentDescription("Shared photo");}}); }
    private void stories() { int expected=revision;add(content,button("Create a story",this::pickPhoto)); LinearLayout list=scroll(content);request("GET","/stories",null,value->{JSONArray items=value.optJSONArray("stories");if(items.length()==0)empty(list,R.drawable.app_icon_story,"A little quiet here","Share a photo from your day. Stories stay for 24 hours.");for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);long age=Math.max(0,System.currentTimeMillis()/1000-item.optLong("created_at"));int remaining=SharedLogic.f_remainingStorySeconds((int)Math.min(age,Integer.MAX_VALUE));if(remaining==0)continue;main.postDelayed(()->{if(foreground&&revision==expected)shell();},remaining*1000L);add(list,label(item.optString("display_name")+" · "+Math.max(1,remaining/3600)+"h remaining",18));media(list,item.optString("media_id"));add(list,label(item.optString("caption"),16));if(item.optString("owner").equals(session.optJSONObject("user").optString("id")))add(list,button("Delete story",()->request("DELETE","/stories/"+item.optString("id"),null,result->shell())));}}); }
    private void account() { LinearLayout list=scroll(content);request("GET","/me",null,value->{add(list,label("@"+value.optString("username"),22));EditText name=field("Display name",false);name.setText(value.optString("display_name"));add(list,name);add(list,button("Save profile",()->request("PATCH","/me",object("display_name",name.getText().toString().trim()),result->notice("Profile saved"))));add(list,button("Sign out",()->request("POST","/auth/logout",null,result->signOut())));add(list,button("Delete account",()->{EditText password=field("Confirm your password",true);new AlertDialog.Builder(this).setTitle("Delete account permanently?").setMessage("Your photos, stories, messages and location will be deleted.").setView(password).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->request("DELETE","/me",object("password",password.getText().toString()),result->signOut())).show();}));}); }
    private ImageButton cameraControl(int icon,String title,Runnable action){ImageButton view=new ImageButton(this);view.setImageResource(icon);view.setImageTintList(android.content.res.ColorStateList.valueOf(Color.WHITE));view.setContentDescription(title);view.setPadding(dp(14),dp(14),dp(14),dp(14));view.setBackground(controlBackground(0xCC292B30,false));view.setOnClickListener(v->action.run());return view;}
    private void cameraScreen() {
        content.setPadding(0,0,0,0);FrameLayout stage=new FrameLayout(this);stage.setBackgroundColor(Color.BLACK);content.addView(stage,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout unavailable=column();unavailable.setGravity(Gravity.CENTER);unavailable.setPadding(dp(32),dp(24),dp(32),dp(112));ImageView icon=new ImageView(this);icon.setImageResource(R.drawable.app_icon_camera);icon.setImageTintList(android.content.res.ColorStateList.valueOf(Color.WHITE));unavailable.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView explanation=label("Starting camera…",17);explanation.setTextColor(Color.WHITE);explanation.setGravity(Gravity.CENTER);add(unavailable,explanation);TextView helper=label("You can always choose a photo from your library.",13);helper.setTextColor(0xFFB8BBC2);helper.setGravity(Gravity.CENTER);add(unavailable,helper);Button tryAgain=primary("Retry camera",()->{if(camera!=null){if(checkSelfPermission(android.Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.start();else requestPermissions(new String[]{android.Manifest.permission.CAMERA},41);}});unavailable.addView(tryAgain,new LinearLayout.LayoutParams(-2,dp(48)));
        LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);controls.setPadding(dp(24),dp(16),dp(24),dp(20));controls.setBackgroundColor(0xCC000000);ImageButton album=cameraControl(R.drawable.app_icon_image,"Choose photo",this::pickPhoto);ImageButton shutter=cameraControl(R.drawable.app_icon_camera,"Take photo",()->{if(camera!=null)camera.capture();});ImageButton flip=cameraControl(R.drawable.app_icon_swap,"Switch camera",()->{if(camera!=null)camera.flip();});android.graphics.drawable.GradientDrawable ring=new android.graphics.drawable.GradientDrawable();ring.setShape(android.graphics.drawable.GradientDrawable.OVAL);ring.setColor(Color.WHITE);ring.setStroke(dp(5),0xFFAAAAAA);shutter.setBackground(ring);shutter.setImageTintList(android.content.res.ColorStateList.valueOf(Color.BLACK));shutter.setPadding(dp(22),dp(22),dp(22),dp(22));shutter.setEnabled(false);flip.setEnabled(false);shutter.setAlpha(0.35f);flip.setAlpha(0.35f);controls.addView(album,new LinearLayout.LayoutParams(dp(52),dp(52)));View left=new View(this);controls.addView(left,new LinearLayout.LayoutParams(0,1,1));controls.addView(shutter,new LinearLayout.LayoutParams(dp(80),dp(80)));View right=new View(this);controls.addView(right,new LinearLayout.LayoutParams(0,1,1));controls.addView(flip,new LinearLayout.LayoutParams(dp(52),dp(52)));
        camera=new NativeCamera(this,this::preview,this::notice,(ready,message)->{unavailable.setVisibility(ready?View.GONE:View.VISIBLE);explanation.setText(message);tryAgain.setVisibility(message.equals("Starting camera…")?View.GONE:View.VISIBLE);shutter.setEnabled(ready);flip.setEnabled(ready);shutter.setAlpha(ready?1:0.35f);flip.setAlpha(ready?1:0.35f);});stage.addView(camera.view(),new FrameLayout.LayoutParams(-1,-1));stage.addView(unavailable,new FrameLayout.LayoutParams(-1,-1));stage.addView(controls,new FrameLayout.LayoutParams(-1,dp(116),Gravity.BOTTOM));
        if(checkSelfPermission(android.Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.start();else{explanation.setText("Camera permission is needed to take a photo.");tryAgain.setVisibility(View.VISIBLE);requestPermissions(new String[]{android.Manifest.permission.CAMERA},41);}
    }
    private void pickPhoto() { Intent intent=Build.VERSION.SDK_INT>=33?new Intent("android.provider.action.PICK_IMAGES"):new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE);intent.setType("image/*");startActivityForResult(intent,42); }
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==42&&result==RESULT_OK&&data!=null&&data.getData()!=null){notice("Preparing photo…");android.net.Uri uri=data.getData();new Thread(()->{try(java.io.InputStream input=getContentResolver().openInputStream(uri)){byte[] bytes=NativeCamera.normalize(input);runOnUiThread(()->{if(!isDestroyed())preview(bytes);});}catch(Exception error){runOnUiThread(()->notice("Could not open photo: "+error.getMessage()));}},"photo-import").start();}}
    private void preview(byte[] bytes) { if(SharedLogic.f_canUploadPhoto(bytes.length)!=1){notice("Photo must be between 1 byte and 8 MiB.");return;}LinearLayout body=column();ImageView image=new ImageView(this);image.setImageBitmap(BitmapFactory.decodeByteArray(bytes,0,bytes.length));image.setScaleType(ImageView.ScaleType.FIT_CENTER);body.addView(image,new LinearLayout.LayoutParams(-1,dp(300)));EditText caption=field("Caption",false);add(body,caption);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Preview photo").setView(body).setNegativeButton("Cancel",null).create();add(body,button("Share to story",()->{if(caption.getText().toString().codePointCount(0,caption.length())>240){notice("Caption must be at most 240 characters.");return;}upload(bytes,mediaId->request("POST","/stories",object("media_id",mediaId.optString("id"),"caption",caption.getText().toString()),value->{dialog.dismiss();notice("Story shared");}));}));add(body,button("Send to conversation",()->{if(conversation!=null){sendPhoto(bytes,conversation,caption.getText().toString().trim(),dialog);return;}request("GET","/conversations",null,value->{JSONArray items=value.optJSONArray("conversations");String[] names=new String[items.length()];for(int i=0;i<names.length;i++)names[i]=items.optJSONObject(i).optString("display_name");if(names.length==0){notice("Start a conversation with a friend first.");return;}new AlertDialog.Builder(this).setTitle("Send photo to").setItems(names,(d,index)->sendPhoto(bytes,items.optJSONObject(index).optString("id"),caption.getText().toString().trim(),dialog)).show();});}));dialog.show(); }
    private void upload(byte[] bytes,Result callback){int expected=revision;notice("Uploading photo…");api.request("POST","/media",null,bytes,false,(value,data,error,code)->{if(expected!=revision)return;if(error!=null)notice(error);else callback.accept(value);});}
    private void sendPhoto(byte[] bytes,String id,String caption,AlertDialog dialog){if(SharedLogic.f_canSendMessage(caption.codePointCount(0,caption.length()),1)!=1){notice("Photo caption must be at most 2,000 characters.");return;}upload(bytes,mediaId->request("POST","/conversations/"+id+"/messages",object("media_id",mediaId.optString("id"),"text",caption),value->{dialog.dismiss();notice("Photo sent");}));}
    private void friendMap() {
        Switch consent=new Switch(this);consent.setText("Share my location for one hour");add(content,consent);
        request("GET","/me",null,value->{locationConsent=value.optBoolean("location_sharing");consent.setChecked(locationConsent);consent.setOnCheckedChangeListener((v,enabled)->{if(changingConsent)return;locationConsent=enabled;if(!enabled){stopLocation();int expected=revision;api.request("PUT","/location",object("enabled",false),null,false,(result,bytes,error,code)->{if(expected!=revision)return;if(error!=null){locationConsent=true;changingConsent=true;consent.setChecked(true);changingConsent=false;notice("Could not turn sharing off. Your last location may remain visible for up to one hour. Retry. "+error);}else notice("Location sharing off");});}else publishLocation();});});
        org.maplibre.android.MapLibre.getInstance(this);mapView=new org.maplibre.android.maps.MapView(this);mapView.onCreate(null);content.addView(mapView,new LinearLayout.LayoutParams(-1,0,1));mapView.onStart();mapView.onResume();
        mapView.addOnDidFailLoadingMapListener(error->notice("Map provider unavailable: "+error));
        mapView.getMapAsync(map->map.setStyle("https://tiles.openfreemap.org/styles/liberty",style->{request("GET","/map",null,value->{JSONArray items=value.optJSONArray("locations");for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);org.maplibre.android.geometry.LatLng point=new org.maplibre.android.geometry.LatLng(item.optInt("latitude_e6")/1e6,item.optInt("longitude_e6")/1e6);map.addMarker(new org.maplibre.android.annotations.MarkerOptions().position(point).title(item.optString("display_name")));if(i==0)map.animateCamera(org.maplibre.android.camera.CameraUpdateFactory.newLatLngZoom(point,10));}if(items.length()==0)notice("Friends who choose to share their location will appear here.");});}));
        add(content,label("© OpenFreeMap · © OpenMapTiles · © OpenStreetMap contributors",10));
    }
    private void publishLocation(){if(!locationConsent || !foreground)return;boolean permission=checkSelfPermission(android.Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;if(SharedLogic.f_shouldPublishLocation(locationConsent?1:0,permission?1:0)!=1){requestPermissions(new String[]{android.Manifest.permission.ACCESS_COARSE_LOCATION,android.Manifest.permission.ACCESS_FINE_LOCATION},43);return;}locations=(android.location.LocationManager)getSystemService(LOCATION_SERVICE);String provider=locations.isProviderEnabled(android.location.LocationManager.GPS_PROVIDER)&&checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED?android.location.LocationManager.GPS_PROVIDER:android.location.LocationManager.NETWORK_PROVIDER;locationListener=new android.location.LocationListener(){public void onLocationChanged(android.location.Location location){stopLocation();if(!foreground||!locationConsent)return;request("PUT","/location",object("enabled",true,"latitude_e6",Math.round(location.getLatitude()*1e6),"longitude_e6",Math.round(location.getLongitude()*1e6)),value->notice("Location shared for one hour. You can turn it off anytime."));}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}public void onStatusChanged(String p,int s,Bundle b){}};try{locations.requestSingleUpdate(provider,locationListener,Looper.getMainLooper());notice("Finding your location…");main.postDelayed(()->{if(locationListener!=null){stopLocation();notice("Location unavailable. Check device location settings and retry.");}},15000);}catch(Exception error){stopLocation();notice("Location unavailable: "+error.getMessage());}}
    private void stopLocation(){if(locations!=null&&locationListener!=null)locations.removeUpdates(locationListener);locationListener=null;}
    private void stopFeatures(){main.removeCallbacksAndMessages(null);stopLocation();if(camera!=null){camera.close();camera=null;}if(mapView!=null){mapView.onPause();mapView.onStop();mapView.onDestroy();mapView=null;}}
    @Override public void onRequestPermissionsResult(int request,String[] names,int[] results){super.onRequestPermissionsResult(request,names,results);if(request==41&&camera!=null){if(results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)camera.start();else notice("Camera permission denied. You can still choose a photo.");}if(request==43){if(locationConsent&&checkSelfPermission(android.Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED)publishLocation();else notice("Location permission denied. Your location was not shared.");}}
    @Override protected void onStart(){super.onStart();foreground=true;}
    @Override protected void onStop(){foreground=false;revision++;stopFeatures();api.cancel();super.onStop();}
    @Override protected void onRestart(){super.onRestart();if(session!=null)shell();}
    @Override protected void onDestroy(){api.close();stopFeatures();super.onDestroy();}
    @Override protected void onSaveInstanceState(Bundle state){state.putInt("tab",selected);state.putString("conversation",conversation);super.onSaveInstanceState(state);}
    @Override public void onBackPressed(){if(conversation!=null){conversation=null;shell();}else if(session!=null)shell();else super.onBackPressed();}
}
