name: dcf_screens
description: "A module for natively navigating between screens in the DCFlight app using Flutter's platform channels."
version: 0.0.1
homepage: https://github.com/squirelboy360/dcflight
repository: https://github.com/squirelboy360/dcflight

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


# framework dependencies (prod)
  # dcflight: ^0.0.1

# framework dependencies (local)
  dcflight:
   path : ../dcflight
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DCFScreens
      android:
        package: com.dotcorr.dcfscreens
        pluginClass: DcfScreensPlugin




