/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dotcorr.android;

public class android_swig {
  public static void setAndroid_view_View(SWIGTYPE_p_class value) {
    android_swigJNI.android_view_View_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_view_View() {
    return new SWIGTYPE_p_class(android_swigJNI.android_view_View_get(), true);
  }

  public static void setAndroid_view_ViewGroup(SWIGTYPE_p_class value) {
    android_swigJNI.android_view_ViewGroup_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_view_ViewGroup() {
    return new SWIGTYPE_p_class(android_swigJNI.android_view_ViewGroup_get(), true);
  }

  public static void setAndroid_widget_TextView(SWIGTYPE_p_class value) {
    android_swigJNI.android_widget_TextView_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_widget_TextView() {
    return new SWIGTYPE_p_class(android_swigJNI.android_widget_TextView_get(), true);
  }

  public static void setAndroid_widget_Button(SWIGTYPE_p_class value) {
    android_swigJNI.android_widget_Button_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_widget_Button() {
    return new SWIGTYPE_p_class(android_swigJNI.android_widget_Button_get(), true);
  }

  public static void setAndroid_widget_ImageView(SWIGTYPE_p_class value) {
    android_swigJNI.android_widget_ImageView_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_widget_ImageView() {
    return new SWIGTYPE_p_class(android_swigJNI.android_widget_ImageView_get(), true);
  }

  public static void setAndroid_app_Activity(SWIGTYPE_p_class value) {
    android_swigJNI.android_app_Activity_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_app_Activity() {
    return new SWIGTYPE_p_class(android_swigJNI.android_app_Activity_get(), true);
  }

  public static void setAndroid_content_Context(SWIGTYPE_p_class value) {
    android_swigJNI.android_content_Context_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_content_Context() {
    return new SWIGTYPE_p_class(android_swigJNI.android_content_Context_get(), true);
  }

  public static void setAndroid_graphics_Canvas(SWIGTYPE_p_class value) {
    android_swigJNI.android_graphics_Canvas_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_graphics_Canvas() {
    return new SWIGTYPE_p_class(android_swigJNI.android_graphics_Canvas_get(), true);
  }

  public static void setAndroid_graphics_Paint(SWIGTYPE_p_class value) {
    android_swigJNI.android_graphics_Paint_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_graphics_Paint() {
    return new SWIGTYPE_p_class(android_swigJNI.android_graphics_Paint_get(), true);
  }

  public static void setAndroid_webkit_WebView(SWIGTYPE_p_class value) {
    android_swigJNI.android_webkit_WebView_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getAndroid_webkit_WebView() {
    return new SWIGTYPE_p_class(android_swigJNI.android_webkit_WebView_get(), true);
  }

}
