/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dotcorr.android;

public class android_swigJNI {
  public final static native void android_view_View_set(long jarg1);
  public final static native long android_view_View_get();
  public final static native void android_view_ViewGroup_set(long jarg1);
  public final static native long android_view_ViewGroup_get();
  public final static native void android_widget_TextView_set(long jarg1);
  public final static native long android_widget_TextView_get();
  public final static native void android_widget_Button_set(long jarg1);
  public final static native long android_widget_Button_get();
  public final static native void android_widget_ImageView_set(long jarg1);
  public final static native long android_widget_ImageView_get();
  public final static native void android_app_Activity_set(long jarg1);
  public final static native long android_app_Activity_get();
  public final static native void android_content_Context_set(long jarg1);
  public final static native long android_content_Context_get();
  public final static native void android_graphics_Canvas_set(long jarg1);
  public final static native long android_graphics_Canvas_get();
  public final static native void android_graphics_Paint_set(long jarg1);
  public final static native long android_graphics_Paint_get();
  public final static native void android_webkit_WebView_set(long jarg1);
  public final static native long android_webkit_WebView_get();
}
