"""Defense-in-depth audit. Native build/link verification supplies stronger evidence."""
import re
from .audit_references import application_identity, source_reference, dex_references, MAX_SOURCE, MAX_DEX, read_source
from pathlib import Path

FORBIDDEN = re.compile(r'\b(dcflight|flutter|flutter_zero|dart:ffi|libdart|DartVM|JavaScriptCore|WKWebView|android\.webkit|ReactNative|libhermes|yoga|FlutterEngine|DartExecutor|FlutterJNI|FlutterLoader|ReactNativeHost|ReactInstanceManager|HermesExecutor)\b', re.I)
SOURCE_SUFFIXES = {'.c', '.h', '.m', '.mm', '.swift', '.java', '.kt', '.gradle', '.kts', '.xml', '.json', '.plist', '.pbxproj', '.xcconfig', '.properties'}


def generated_integrity(output):
    """Verify current generated bytes against the local synchronization baseline."""
    import json
    from .sync import safe_path, digest
    root = Path(output).absolute()
    findings = []
    checked = 0
    try:
        if root.is_symlink():
            raise ValueError('Symlink output root')
        manifest = safe_path(root, '.dcflight/state.json')
        if not manifest.is_file():
            return {'status': 'unknown', 'checkedFiles': 0,
                    'findings': [], 'reason': 'No synchronization baseline'}
        def unique_pairs(pairs):
            result = {}
            for key, value in pairs:
                if key in result:
                    raise ValueError('Duplicate synchronization metadata key')
                result[key] = value
            return result
        state = json.loads(manifest.read_text(), object_pairs_hook=unique_pairs)
        if not isinstance(state, dict) or state.get('version') != 1 or not isinstance(state.get('files'), dict):
            raise ValueError('Invalid synchronization baseline')
        for relative, entry in sorted(state['files'].items()):
            if (not isinstance(entry, dict) or entry.get('ownership') not in ('generated', 'user')
                    or not isinstance(entry.get('sha256'), str)
                    or not re.fullmatch('[0-9a-f]{64}', entry['sha256'])):
                raise ValueError('Invalid synchronization entry: ' + relative)
            path = safe_path(root, relative)
            if entry['ownership'] == 'user':
                continue
            checked += 1
            if not path.is_file():
                findings.append(relative + ': generated file is missing')
            elif digest(path.read_bytes()) != entry['sha256']:
                findings.append(relative + ': generated file differs from synchronization baseline')
    except (ValueError, OSError) as error:
        findings.append('Cannot verify generated source: ' + str(error))
    return {'status': 'changed' if findings else 'matched', 'checkedFiles': checked,
            'findings': findings,
            'scope': 'Local generated bytes only; user-owned additions, native build products and visual parity are not certified. Baseline is not a signed attestation.'}


def source_consistency(output):
    """Compare generation inputs, not installed binaries or visual output."""
    import json
    root = Path(output)
    path = root / '.dcflight/source.json'
    if not path.is_file():
        return {'status': 'unknown', 'reason': 'No generation input receipt'}
    receipt = json.loads(path.read_text())
    targets = receipt.get('targets', {})
    present = [name for name in ('ios', 'android') if (root / name).is_dir()]
    missing = [name for name in present if name not in targets]
    if missing:
        return {'status': 'unknown', 'reason': 'Regenerate platforms to record their inputs', 'missing': missing}
    if len(present) < 2:
        return {'status': 'singleTarget', 'targets': present}
    values = [targets[name] for name in present]
    same = all(value == values[0] for value in values[1:])
    return {'status': 'matched' if same else 'mismatched', 'targets': present,
            'generatorIdentityRecorded': all(isinstance(value.get('generator'), dict) for value in values),
            'scope': 'Recorded authoring, typed IR, compiler/mapping identity when available, and shared logic inputs; does not prove current native edits, builds or installed app identity.'}


def audit(output):
    root = Path(output)
    findings = []
    checked = 0
    try: app_id = application_identity(root)
    except (ValueError, OSError, AttributeError):
        app_id = None; findings.append('Cannot verify application identity')
    for target in ('ios', 'android'):
        folder = root / target
        if not folder.exists():
            continue
        for path in folder.rglob('*'):
            relative = path.relative_to(root).as_posix()
            if any(relative.startswith(prefix) for prefix in ('android/app/build/','android/build/','android/.gradle/','ios/build/')):
                continue
            if path.is_symlink():
                findings.append(str(path.relative_to(root)) + ': symlink not auditable')
            elif path.is_file() and path.suffix in SOURCE_SUFFIXES:
                checked += 1
                if path.stat().st_size > MAX_SOURCE:
                    findings.append(relative + ': source exceeds audit bound'); continue
                try: prohibited = source_reference(read_source(path), path.suffix, app_id)
                except (ValueError, OSError, SyntaxError): prohibited = True
                if prohibited:
                    findings.append(str(path.relative_to(root)) + ': prohibited runtime reference')
    if checked == 0:
        raise ValueError('No native source/project files found')
    integrity = generated_integrity(root)
    findings.extend(integrity['findings'])
    try:
        consistency = source_consistency(root)
    except (ValueError, OSError, AttributeError, TypeError, KeyError):
        consistency = {'status': 'unknown', 'reason': 'Invalid generation input receipt'}
        findings.append('Cannot verify generation input receipt')
    if consistency['status'] == 'mismatched':
        findings.append('Native projects were generated from different shared inputs; regenerate both platforms')
    return {'checkedFiles': checked, 'findings': findings, 'passed': not findings,
            'sourceConsistency': consistency,
            'generatedIntegrity': integrity,
            'scope': 'Source/project scan; use native builds and dependency inspection to verify linked artifacts.'}


def audit_apk(apk, expected_libraries=None, *, application_id=None):
    """Only exact audited application and locked native-package libraries may ship."""
    import hashlib
    import zipfile
    expected_libraries = expected_libraries or {}
    with zipfile.ZipFile(apk) as archive:
        names = archive.namelist()
        if len(names)>65536 or len(names)!=len(set(names)):raise ValueError('Oversized or duplicate APK entries')
        dex_reports = []
        libraries = {name for name in names if name.startswith('lib/') and not name.endswith('/')}
        if libraries != set(expected_libraries):
            raise ValueError('Unexpected APK native libraries: ' + str(libraries ^ set(expected_libraries)))
        if any(FORBIDDEN.search(Path(name).name) or Path(name).name.lower() in ('libflutter.so','libreactnative.so','libjsc.so','libv8.so') for name in libraries):raise ValueError('Prohibited runtime native library')
        for name, expected_sha in expected_libraries.items():
            if hashlib.sha256(archive.read(name)).hexdigest() != expected_sha:
                raise ValueError('APK native library hash differs from audited generation or package lock: ' + name)
        if any(name.lower().endswith(('.dart', '.js', '.wasm', '.dill', '.snapshot')) for name in names):
            raise ValueError('Unexpected runtime source/engine payload in APK')
        for name in names:
            if name.endswith('.dex'):
                if archive.getinfo(name).file_size > MAX_DEX:raise ValueError('DEX exceeds audit bound')
                report=dex_references(archive.read(name),application_id)
                if report['prohibitedTypes'] or report['dynamicRuntimeNames']:
                    raise ValueError('Forbidden runtime reference in APK DEX')
                dex_reports.append({'entry':name,**report})
    return {'passed': True, 'auditedLibraries': sorted(expected_libraries),
            'dex':dex_reports,'applicationIdentity':application_id,
            'scope':'Exact native library hashes, runtime payload extensions, DEX types and recognizable dynamic names. Not a proof against renamed/obfuscated engines or arbitrary native behavior.'}
