/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040301
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#include <jni.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1view_1View_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_view_View = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1view_1View_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_view_View;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1view_1ViewGroup_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_view_ViewGroup = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1view_1ViewGroup_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_view_ViewGroup;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1TextView_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_widget_TextView = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1TextView_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_widget_TextView;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1Button_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_widget_Button = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1Button_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_widget_Button;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1ImageView_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_widget_ImageView = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1widget_1ImageView_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_widget_ImageView;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1app_1Activity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_app_Activity = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1app_1Activity_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_app_Activity;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1content_1Context_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_content_Context = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1content_1Context_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_content_Context;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1graphics_1Canvas_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_graphics_Canvas = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1graphics_1Canvas_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_graphics_Canvas;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1graphics_1Paint_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_graphics_Paint = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1graphics_1Paint_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_graphics_Paint;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1webkit_1WebView_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  class arg1 ;
  class *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(class **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null class");
    return ;
  }
  arg1 = *argp1; 
  android_webkit_WebView = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_dotcorr_android_android_1swigJNI_android_1webkit_1WebView_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  class result;
  
  (void)jenv;
  (void)jcls;
  result = android_webkit_WebView;
  {
    class * resultptr = (class *) malloc(sizeof(class));
    memmove(resultptr, &result, sizeof(class));
    *(class **)&jresult = resultptr;
  }
  return jresult;
}


#ifdef __cplusplus
}
#endif

