name: dcflight
description: "Pure Dart Native UI Framework with FFI"
version: 0.0.3
homepage: https://github.com/Dotcorr/dcflight
repository: https://github.com/Dotcorr/dcflight

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # FFI dependencies
  ffi: ^2.1.0
  jni: ^0.5.0
  # Framework dependencies
  equatable: ^2.0.7
  objective_c: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # FFI generation
  ffigen: ^12.0.0
  jnigen: ^0.14.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DCFAppDelegate  # Only divergence code
      android:
        package: com.dotcorr.dcflight  # Only divergence code
        pluginClass: DcflightPlugin

# FFI generation configuration
ffigen:
  output: 'lib/ffi/yoga_ffi.dart'
  headers:
    entry-points:
      - 'yoga_headers/YGNode.h'
      - 'yoga_headers/YGNodeStyle.h'
      - 'yoga_headers/YGNodeLayout.h'
    include-directives:
      - 'yoga_headers/YGNode.h'
      - 'yoga_headers/YGNodeStyle.h'
      - 'yoga_headers/YGNodeLayout.h'
  compiler-opts:
    - '-Iyoga_headers'
  functions:
    include:
      - 'YGNode.*'
      - 'YGConfig.*'
      - 'YGLayout.*'
      - 'YGStyle.*'
      - 'YGEnums.*'